# 
control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_obs: 96

max_cmd: [0.8, 0.5, 1.57]

clip_action: 100
clip_observation: 100
history_length: 5

# idx: sim order, value: real motor id
upper_body_joint2motor_idx: [15, 22, 16, 23, 17, 24, 18, 25, 19, 26, 20, 27, 21, 28]
upper_body_kps: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40]
upper_body_kds: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
upper_body_default_pos: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] #TODO: print check

# idx: sim order, value: real motor id
lower_body_joint2motor_idx: [12, 13, 14, 0, 6, 1, 7, 2, 8, 3, 9, 4, 10, 5, 11]
lower_body_kps: [200, 40, 40, 100, 100, 100, 100, 100, 100, 150, 150, 40, 40, 40, 40]
lower_body_kds: [5, 5, 5, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2]
lower_body_default_pos: [0, 0, 0, -0.1, -0.1, 0, 0, 0, 0, 0.3, 0.3, -0.2, -0.2, 0, 0] #TODO: print check

# idx: sim order, value: real motor id
whole_body_motor2joint_idx: [0, 3, 6, 9, 13, 17, 1, 4, 7, 10, 14, 18, 2, 5, 8, 11, 15, 19, 21, 23, 25, 27, 12, 16, 20, 22, 24, 26, 28]
whole_body_joint2motor_idx: [0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 15, 22, 4, 10, 16, 23, 5, 11, 17, 24, 18, 25, 19, 26, 20, 27, 21, 28]
whole_body_default_pos: [-0.1, -0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.3, 0.0,
  0.0, -0.2, -0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0] # order: sim order
num_upper_actions: 14
num_lower_actions: 15
num_actions: 29
